name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Use Node 20.x
      - name: Use Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache-dependency-path: yarn.lock
          cache: "yarn"

      # Install Packages
      - name: Install Packages
        run: yarn install --frozen-lockfile

      # Run Lint
      - name: Run Lint
        run: yarn lint

      # Run Unit Tests
      - name: Run Unit Tests
        run: yarn test

      # Upload Coverage Artifact
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
