name: Release iOS

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install Dependencies
      - name: Install Dependencies
        run: bun install

      # Run Lint
      - name: Run Lint
        run: bun run lint

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install Dependencies
      - name: Install Dependencies
        run: bun install

      # Run Unit Tests
      - name: Run Unit Tests
        run: bun run test

      # Upload Coverage Artifact
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  eas-build:
    name: EAS Build
    runs-on: ubuntu-latest
    needs: [lint, unit-tests]
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Expo and EAS
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Trigger EAS Build
      - name: Trigger EAS Build
        run: eas build --platform ios --profile production --non-interactive
